### ISSUE TITLE
Please follow submission guidelines

### ISSUE THREAD

**Issue by cnihackathon22** [mdrazak2001/BMTC_DataScience_Challenge#1]
Dear Participant, 

Please follow the submission guidelines given on [this link](https://www.cnihackathon.in/datasciencechallenge.html#submission).
It seems that currently, your submission does not meet the requirement.

Regards, 
CNI Hackathon Organizing Team

**Comment by mdrazak2001** [comment]
Hi, 
I have updated the structure accordingly.
Please close the issue.

Thanks,
Razak
